ALTER TABLE bot_modes
	ADD COLUMN IF NOT EXISTS keyword_name TEXT NOT NULL DEFAULT '',
	ADD COLUMN IF NOT EXISTS keyword_description TEXT NOT NULL DEFAULT '',
	ADD COLUMN IF NOT EXISTS keyword_response TEXT NOT NULL DEFAULT '',
	ADD COLUMN IF NOT EXISTS coordinated_twitch_title TEXT NOT NULL DEFAULT '';
